search_api.backend.plugin.postgresql:
  type: mapping
  label: 'PostgreSQL backend configuration'
  mapping:
    connection:
      type: mapping
      label: 'Database connection settings'
      mapping:
        database:
          type: string
          label: 'Database name'
        host:
          type: string
          label: 'Database host'
        port:
          type: integer
          label: 'Database port'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'

search_api.backend.plugin.postgresql_azure:
  type: mapping
  label: 'PostgreSQL with Azure AI Vector Search backend configuration'
  mapping:
    connection:
      type: mapping
      label: 'Database connection settings'
      mapping:
        database:
          type: string
          label: 'Database name'
        host:
          type: string
          label: 'Database host'
        port:
          type: integer
          label: 'Database port'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'
    azure_embedding:
      type: mapping
      label: 'Azure AI embedding configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable Azure AI vector search'
        service_type:
          type: string
          label: 'Azure AI service type'
        endpoint:
          type: string
          label: 'Azure OpenAI endpoint'
        api_key:
          type: string
          label: 'Azure OpenAI API key'
        deployment_name:
          type: string
          label: 'Azure OpenAI deployment name'
        api_version:
          type: string
          label: 'Azure OpenAI API version'
        dimension:
          type: integer
          label: 'Embedding dimension'
        model_type:
          type: string
          label: 'Embedding model type'
    vector_index:
      type: mapping
      label: 'Vector index configuration'
      mapping:
        method:
          type: string
          label: 'Vector index method'
        ivfflat_lists:
          type: integer
          label: 'IVFFlat lists parameter'
        hnsw_m:
          type: integer
          label: 'HNSW m parameter'
        hnsw_ef_construction:
          type: integer
          label: 'HNSW ef_construction parameter'
    hybrid_search:
      type: mapping
      label: 'Hybrid search configuration'
      mapping:
        text_weight:
          type: float
          label: 'Text search weight'
        vector_weight:
          type: float
          label: 'Vector search weight'
        similarity_threshold:
          type: float
          label: 'Similarity threshold'
        max_vector_results:
          type: integer
          label: 'Maximum vector search results'
    azure_optimization:
      type: mapping
      label: 'Azure optimization settings'
      mapping:
        batch_embedding:
          type: boolean
          label: 'Enable batch embedding'
        batch_size:
          type: integer
          label: 'Embedding batch size'
        retry_attempts:
          type: integer
          label: 'API retry attempts'
        timeout:
          type: integer
          label: 'API timeout'
        rate_limit_delay:
          type: integer
          label: 'Rate limit delay'