search_api.backend.plugin.postgresql:
  type: mapping
  label: 'PostgreSQL backend configuration'
  mapping:
    connection:
      type: mapping
      label: 'Database connection settings'
      mapping:
        database:
          type: string
          label: 'Database name'
        host:
          type: string
          label: 'Database host'
        port:
          type: integer
          label: 'Database port'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'
    ai_embeddings:
      type: mapping
      label: 'AI Text Embeddings Configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable AI text embeddings'
        hybrid_search:
          type: boolean
          label: 'Enable hybrid search (FTS + Vector)'
        azure_ai:
          type: mapping
          label: 'Azure AI Services Configuration'
          mapping:
            endpoint:
              type: string
              label: 'Azure AI Services endpoint'
            api_key_storage:
              type: string
              label: 'API key storage method'
            api_key:
              type: string
              label: 'API key (for direct storage)'
            key_name:
              type: string
              label: 'Key storage name'
            model:
              type: string
              label: 'Embedding model'
            dimensions:
              type: integer
              label: 'Vector dimensions'
            batch_size:
              type: integer
              label: 'Embedding batch size'
        similarity_threshold:
          type: float
          label: 'Vector similarity threshold'
        weight_vector:
          type: float
          label: 'Vector search weight in hybrid mode'
        weight_fulltext:
          type: float
          label: 'Full-text search weight in hybrid mode'