# Schema for Search API PostgreSQL module configuration

# Standard PostgreSQL backend configuration
search_api.backend.plugin.postgresql:
  type: config_object
  label: 'PostgreSQL search backend'
  mapping:
    connection:
      type: mapping
      label: 'Database connection'
      mapping:
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
        database:
          type: string
          label: 'Database name'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password (optional)'
          # UPDATED: Password is now explicitly optional - no 'required' constraint
        password_key:
          type: string
          label: 'Password key reference (Key module) - optional'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        ssl_ca:
          type: string
          label: 'Path to SSL certificate'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'
    ai_embeddings:
      type: mapping
      label: 'AI Embeddings configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable AI embeddings'
        azure_ai:
          type: mapping
          label: 'Azure AI configuration'
          mapping:
            endpoint:
              type: string
              label: 'Azure OpenAI endpoint'
            api_key:
              type: string
              label: 'API key (deprecated - use api_key_name instead)'
            api_key_name:
              type: string
              label: 'API key name (Key module)'
            deployment_name:
              type: string
              label: 'Deployment name'
            model:
              type: string
              label: 'Embedding model'
            dimension:
              type: integer
              label: 'Vector dimension'

# Azure PostgreSQL backend configuration
search_api.backend.plugin.postgresql_azure:
  type: config_object
  label: 'Azure PostgreSQL search backend'
  mapping:
    connection:
      type: mapping
      label: 'Database connection'
      mapping:
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
        database:
          type: string
          label: 'Database name'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password (optional)'
          # UPDATED: Password is optional for all backend types
        password_key:
          type: string
          label: 'Password key reference (Key module) - optional'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        ssl_ca:
          type: string
          label: 'Path to SSL certificate'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'
    vector_search:
      type: mapping
      label: 'Vector search configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable vector search'
        provider:
          type: string
          label: 'Vector provider'
        api_key:
          type: string
          label: 'API key (deprecated)'
        api_key_name:
          type: string
          label: 'API key name (Key module)'
        model:
          type: string
          label: 'Embedding model'
        dimension:
          type: integer
          label: 'Vector dimension'
    vector_index:
      type: mapping
      label: 'Vector index configuration'
      mapping:
        method:
          type: string
          label: 'Index method'
        ivfflat_lists:
          type: integer
          label: 'IVFFlat lists'
        hnsw_m:
          type: integer
          label: 'HNSW M parameter'
        hnsw_ef_construction:
          type: integer
          label: 'HNSW ef_construction parameter'
    hybrid_search:
      type: mapping
      label: 'Hybrid search configuration'
      mapping:
        text_weight:
          type: float
          label: 'Text search weight'
        vector_weight:
          type: float
          label: 'Vector search weight'
        similarity_threshold:
          type: float
          label: 'Similarity threshold'

# Vector PostgreSQL backend configuration
search_api.backend.plugin.postgresql_vector:
  type: config_object
  label: 'PostgreSQL Vector search backend'
  mapping:
    connection:
      type: mapping
      label: 'Database connection'
      mapping:
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
        database:
          type: string
          label: 'Database name'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password (optional)'
          # UPDATED: Password is optional for all backend types
        password_key:
          type: string
          label: 'Password key reference (Key module) - optional'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        ssl_ca:
          type: string
          label: 'Path to SSL certificate'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'
    vector_search:
      type: mapping
      label: 'Vector search configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable vector search'
        provider:
          type: string
          label: 'Vector provider (openai, huggingface, etc.)'
        api_key:
          type: string
          label: 'API key (deprecated - use api_key_name)'
        api_key_name:
          type: string
          label: 'API key name (Key module)'
        model:
          type: string
          label: 'Embedding model'
        dimension:
          type: integer
          label: 'Vector dimension'
        api_base:
          type: string
          label: 'API base URL (for custom endpoints)'
    vector_index:
      type: mapping
      label: 'Vector index configuration'
      mapping:
        method:
          type: string
          label: 'Index method (ivfflat, hnsw)'
        ivfflat_lists:
          type: integer
          label: 'IVFFlat lists parameter'
        hnsw_m:
          type: integer
          label: 'HNSW M parameter'
        hnsw_ef_construction:
          type: integer
          label: 'HNSW ef_construction parameter'
        hnsw_ef_search:
          type: integer
          label: 'HNSW ef_search parameter'
    hybrid_search:
      type: mapping
      label: 'Hybrid search configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable hybrid search'
        text_weight:
          type: float
          label: 'Text search weight (0.0-1.0)'
        vector_weight:
          type: float
          label: 'Vector search weight (0.0-1.0)'
        similarity_threshold:
          type: float
          label: 'Minimum similarity threshold'
        rerank:
          type: boolean
          label: 'Enable result reranking'