# Unified PostgreSQL backend configuration
search_api.backend.plugin.postgresql:
  type: config_object
  label: 'PostgreSQL search backend with AI vector search'
  mapping:
    # Standard Search API DB fields (REQUIRED for compatibility)
    database:
      type: string
      label: 'Database identifier'
    min_chars:
      type: integer
      label: 'Minimum word length'
    matching:
      type: string
      label: 'Partial matching mode'
    autocomplete:
      type: mapping
      label: 'Autocomplete settings'
      mapping:
        suggest_suffix:
          type: boolean
          label: 'Suggest word endings'
        suggest_words:
          type: boolean
          label: 'Suggest additional words'
    
    # PostgreSQL-specific connection configuration
    connection:
      type: mapping
      label: 'Database connection'
      mapping:
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
        database:
          type: string
          label: 'Database name'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password (optional)'
        password_key:
          type: string
          label: 'Password key reference (Key module) - optional'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        ssl_ca:
          type: string
          label: 'Path to SSL certificate'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    
    # PostgreSQL-specific indexing configuration
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'
    
    # AI Embeddings configuration
    ai_embeddings:
      type: mapping
      label: 'AI Embeddings configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable AI embeddings'
        provider:
          type: string
          label: 'AI provider (azure or openai)'
        azure:
          type: mapping
          label: 'Azure OpenAI configuration'
          mapping:
            endpoint:
              type: string
              label: 'Azure OpenAI endpoint'
            api_key:
              type: string
              label: 'Azure OpenAI API key'
            api_key_name:
              type: string
              label: 'Azure OpenAI API key name (Key module)'
            deployment_name:
              type: string
              label: 'Azure deployment name'
            api_version:
              type: string
              label: 'Azure API version'
            model:
              type: string
              label: 'Embedding model'
            dimension:
              type: integer
              label: 'Vector dimension'
        openai:
          type: mapping
          label: 'OpenAI configuration'
          mapping:
            api_key:
              type: string
              label: 'OpenAI API key'
            api_key_name:
              type: string
              label: 'OpenAI API key name (Key module)'
            model:
              type: string
              label: 'Embedding model'
            organization:
              type: string
              label: 'OpenAI organization'
            base_url:
              type: string
              label: 'OpenAI base URL'
            dimension:
              type: integer
              label: 'Vector dimension'
        batch_size:
          type: integer
          label: 'AI batch size'
        rate_limit_delay:
          type: integer
          label: 'Rate limit delay (ms)'
        max_retries:
          type: integer
          label: 'Maximum retries'
        timeout:
          type: integer
          label: 'Request timeout (seconds)'
        enable_cache:
          type: boolean
          label: 'Enable embedding cache'
        cache_ttl:
          type: integer
          label: 'Cache TTL (seconds)'
    
    # Vector Index configuration
    vector_index:
      type: mapping
      label: 'Vector index configuration'
      mapping:
        method:
          type: string
          label: 'Vector index method'
        lists:
          type: integer
          label: 'Number of lists (for IVFFlat)'
        probes:
          type: integer
          label: 'Number of probes'
        distance:
          type: string
          label: 'Distance function'
    
    # Hybrid Search configuration
    hybrid_search:
      type: mapping
      label: 'Hybrid search configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable hybrid search'
        text_weight:
          type: float
          label: 'Text search weight'
        vector_weight:
          type: float
          label: 'Vector search weight'
        similarity_threshold:
          type: float
          label: 'Similarity threshold'
        max_results:
          type: integer
          label: 'Maximum results'
    
    # Performance configuration
    performance:
      type: mapping
      label: 'Performance configuration'
      mapping:
        connection_pool_size:
          type: integer
          label: 'Connection pool size'
        statement_timeout:
          type: integer
          label: 'Statement timeout (ms)'
        work_mem:
          type: string
          label: 'Work memory setting'
        effective_cache_size:
          type: string
          label: 'Effective cache size'

# Legacy backend configurations (for backward compatibility)
search_api.backend.plugin.postgresql_azure:
  type: search_api.backend.plugin.postgresql

search_api.backend.plugin.postgresql_vector:
  type: search_api.backend.plugin.postgresql

# Dashboard configuration
search_api_postgresql.dashboard:
  type: config_object
  label: 'Search API PostgreSQL dashboard settings'
  mapping:
    analytics:
      type: mapping
      label: 'Analytics settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable analytics tracking'
        retention_days:
          type: integer
          label: 'Data retention period (days)'
    display:
      type: mapping
      label: 'Display settings'
      mapping:
        items_per_page:
          type: integer
          label: 'Items per page'
        refresh_interval:
          type: integer
          label: 'Auto-refresh interval (seconds)'
        show_costs:
          type: boolean
          label: 'Show cost information'
    alerts:
      type: mapping
      label: 'Alert settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable alerts'
        cost_threshold:
          type: float
          label: 'Daily cost threshold (USD)'
        error_threshold:
          type: integer
          label: 'Error count threshold'

# Module settings
search_api_postgresql.settings:
  type: config_object
  label: 'Search API PostgreSQL module settings'
  mapping:
    analytics:
      type: mapping
      label: 'Analytics configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable analytics collection'
        track_costs:
          type: boolean
          label: 'Track API costs'
        track_performance:
          type: boolean
          label: 'Track performance metrics'
        anonymize_queries:
          type: boolean
          label: 'Anonymize search queries'
    security:
      type: mapping
      label: 'Security configuration'
      mapping:
        require_https:
          type: boolean
          label: 'Require HTTPS for API calls'
        validate_ssl:
          type: boolean
          label: 'Validate SSL certificates'
        max_api_calls_per_minute:
          type: integer
          label: 'Maximum API calls per minute'
    performance:
      type: mapping
      label: 'Performance configuration'
      mapping:
        default_timeout:
          type: integer
          label: 'Default API timeout (seconds)'
        max_concurrent_requests:
          type: integer
          label: 'Maximum concurrent requests'
        cache_enabled:
          type: boolean
          label: 'Enable result caching'
        cache_ttl:
          type: integer
          label: 'Cache TTL (seconds)'