# Schema definition

search_api.backend.plugin.postgresql:
  type: config_object
  label: 'PostgreSQL search backend with AI vector search'
  mapping:
    # PostgreSQL-specific connection configuration
    connection:
      type: mapping
      label: 'Database connection'
      mapping:
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
        database:
          type: string
          label: 'Database name'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password (optional for passwordless auth)'
        password_key:
          type: string
          label: 'Password key reference (Key module)'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        ssl_ca:
          type: string
          label: 'Path to SSL certificate'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    
    # PostgreSQL-specific indexing configuration
    index_prefix:
      type: string
      label: 'Index table prefix'
    fts_configuration:
      type: string
      label: 'PostgreSQL FTS configuration'
    debug:
      type: boolean
      label: 'Debug mode'
    batch_size:
      type: integer
      label: 'Indexing batch size'
    
    # AI Embeddings configuration
    ai_embeddings:
      type: mapping
      label: 'AI embeddings configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable AI embeddings'
        provider:
          type: string
          label: 'AI service provider'
        azure:
          type: mapping
          label: 'Azure OpenAI configuration'
          mapping:
            endpoint:
              type: string
              label: 'Azure OpenAI endpoint'
            api_key:
              type: string
              label: 'API key'
            api_key_key:
              type: string
              label: 'API key reference (Key module)'
            deployment_name:
              type: string
              label: 'Deployment name'
            model:
              type: string
              label: 'Embedding model'
            dimension:
              type: integer
              label: 'Vector dimensions'
            api_version:
              type: string
              label: 'API version'
        openai:
          type: mapping
          label: 'OpenAI direct configuration'
          mapping:
            api_key:
              type: string
              label: 'API key'
            api_key_key:
              type: string
              label: 'API key reference (Key module)'
            model:
              type: string
              label: 'Embedding model'
            dimension:
              type: integer
              label: 'Vector dimensions'
            organization:
              type: string
              label: 'Organization ID'
        cache:
          type: boolean
          label: 'Enable embedding cache'
        cache_ttl:
          type: integer
          label: 'Cache TTL (seconds)'
    
    # Vector Index configuration
    vector_index:
      type: mapping
      label: 'Vector index configuration'
      mapping:
        method:
          type: string
          label: 'Index method (ivfflat, hnsw)'
        lists:
          type: integer
          label: 'Number of lists for IVFFLAT'
        probes:
          type: integer
          label: 'Number of probes for IVFFLAT'
        distance:
          type: string
          label: 'Distance metric (cosine, l2, inner_product)'
    
    # Hybrid Search configuration
    hybrid_search:
      type: mapping
      label: 'Hybrid search configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable hybrid search'
        text_weight:
          type: float
          label: 'Text search weight (0.0-1.0)'
        vector_weight:
          type: float
          label: 'Vector search weight (0.0-1.0)'
        similarity_threshold:
          type: float
          label: 'Minimum similarity threshold'
        max_results:
          type: integer
          label: 'Maximum results to return'
    
    # Performance configuration
    performance:
      type: mapping
      label: 'Performance configuration'
      mapping:
        connection_pool_size:
          type: integer
          label: 'Connection pool size'
        statement_timeout:
          type: integer
          label: 'Statement timeout (ms)'
        work_mem:
          type: string
          label: 'PostgreSQL work_mem setting'
        effective_cache_size:
          type: string
          label: 'PostgreSQL effective_cache_size setting'

# Embedding cache configuration schema
search_api_postgresql.embedding_cache:
  type: config_object
  label: 'Search API PostgreSQL embedding cache settings'
  mapping:
    default_ttl:
      type: integer
      label: 'Default TTL in seconds'
    max_entries:
      type: integer
      label: 'Maximum cache entries'
    cleanup_probability:
      type: float
      label: 'Cleanup probability (0.0-1.0)'
    enable_compression:
      type: boolean
      label: 'Enable compression'
    table_name:
      type: string
      label: 'Cache table name'

# Dashboard configuration
search_api_postgresql.dashboard:
  type: config_object
  label: 'Search API PostgreSQL dashboard settings'
  mapping:
    display:
      type: mapping
      label: 'Display settings'
      mapping:
        items_per_page:
          type: integer
          label: 'Items per page'
        refresh_interval:
          type: integer
          label: 'Auto-refresh interval (seconds)'
        show_costs:
          type: boolean
          label: 'Show cost information'
    alerts:
      type: mapping
      label: 'Alert settings'
      mapping:
        enabled:
          type: boolean
          label: 'Enable alerts'
        cost_threshold:
          type: float
          label: 'Daily cost threshold (USD)'
        error_threshold:
          type: integer
          label: 'Error count threshold'

# Module settings
search_api_postgresql.settings:
  type: config_object
  label: 'Search API PostgreSQL module settings'
  mapping:
    analytics:
      type: mapping
      label: 'Analytics configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable analytics collection'
        track_costs:
          type: boolean
          label: 'Track API costs'
        track_performance:
          type: boolean
          label: 'Track performance metrics'
        anonymize_queries:
          type: boolean
          label: 'Anonymize search queries'
    security:
      type: mapping
      label: 'Security configuration'
      mapping:
        require_https:
          type: boolean
          label: 'Require HTTPS for API calls'
        validate_ssl:
          type: boolean
          label: 'Validate SSL certificates'
        max_api_calls_per_minute:
          type: integer
          label: 'Maximum API calls per minute'
    performance:
      type: mapping
      label: 'Performance configuration'
      mapping:
        default_timeout:
          type: integer
          label: 'Default API timeout (seconds)'
        max_concurrent_requests:
          type: integer
          label: 'Maximum concurrent requests'
        cache_enabled:
          type: boolean
          label: 'Enable result caching'
        cache_ttl:
          type: integer
          label: 'Cache TTL (seconds)'
