# config/schema/search_api_postgresql.schema.yml

search_api.backend.plugin.postgresql:
  type: config_object
  label: 'PostgreSQL search backend with AI features'
  mapping:
    connection:
      type: mapping
      label: 'Database connection'
      mapping:
        host:
          type: string
          label: 'Host'
        port:
          type: integer
          label: 'Port'
        database:
          type: string
          label: 'Database name'
        username:
          type: string
          label: 'Username'
        password:
          type: string
          label: 'Password (optional)'
        password_key:
          type: string
          label: 'Password key reference (Key module)'
        ssl_mode:
          type: string
          label: 'SSL Mode'
        ssl_ca:
          type: string
          label: 'Path to SSL certificate'
        options:
          type: sequence
          label: 'Additional PDO options'
          sequence:
            type: string
    
    search_settings:
      type: mapping
      label: 'Search settings'
      mapping:
        index_prefix:
          type: string
          label: 'Index table prefix'
        fts_configuration:
          type: string
          label: 'PostgreSQL FTS configuration'
        batch_size:
          type: integer
          label: 'Indexing batch size'
        debug:
          type: boolean
          label: 'Debug mode'
    
    ai_features:
      type: mapping
      label: 'AI Features configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable AI features'
        provider:
          type: string
          label: 'AI provider'
        openai:
          type: mapping
          label: 'OpenAI configuration'
          mapping:
            api_key:
              type: string
              label: 'API key (deprecated)'
            api_key_name:
              type: string
              label: 'API key name (Key module)'
            model:
              type: string
              label: 'Embedding model'
            organization:
              type: string
              label: 'Organization'
            base_url:
              type: string
              label: 'Base URL'
            dimension:
              type: integer
              label: 'Vector dimension'
        azure_openai:
          type: mapping
          label: 'Azure OpenAI configuration'
          mapping:
            endpoint:
              type: string
              label: 'Azure OpenAI endpoint'
            api_key:
              type: string
              label: 'API key (deprecated)'
            api_key_name:
              type: string
              label: 'API key name (Key module)'
            deployment_name:
              type: string
              label: 'Deployment name'
            model:
              type: string
              label: 'Embedding model'
            dimension:
              type: integer
              label: 'Vector dimension'
            api_version:
              type: string
              label: 'API version'
        huggingface:
          type: mapping
          label: 'Hugging Face configuration'
          mapping:
            api_key:
              type: string
              label: 'API key (deprecated)'
            api_key_name:
              type: string
              label: 'API key name (Key module)'
            model:
              type: string
              label: 'Model name'
            dimension:
              type: integer
              label: 'Vector dimension'
        local:
          type: mapping
          label: 'Local model configuration'
          mapping:
            model_path:
              type: string
              label: 'Model path'
            model_type:
              type: string
              label: 'Model type'
            dimension:
              type: integer
              label: 'Vector dimension'
        batch_size:
          type: integer
          label: 'Batch size'
        rate_limit_delay:
          type: integer
          label: 'Rate limit delay'
        max_retries:
          type: integer
          label: 'Max retries'
        timeout:
          type: integer
          label: 'Timeout'
        enable_cache:
          type: boolean
          label: 'Enable cache'
        cache_ttl:
          type: integer
          label: 'Cache TTL'
    
    vector_index:
      type: mapping
      label: 'Vector index configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable vector indexing'
        method:
          type: string
          label: 'Index method'
        ivfflat_lists:
          type: integer
          label: 'IVFFlat lists'
        hnsw_m:
          type: integer
          label: 'HNSW M parameter'
        hnsw_ef_construction:
          type: integer
          label: 'HNSW ef_construction'
        distance:
          type: string
          label: 'Distance metric'
        probes:
          type: integer
          label: 'Probes'
    
    hybrid_search:
      type: mapping
      label: 'Hybrid search configuration'
      mapping:
        enabled:
          type: boolean
          label: 'Enable hybrid search'
        text_weight:
          type: float
          label: 'Text search weight'
        vector_weight:
          type: float
          label: 'Vector search weight'
        similarity_threshold:
          type: float
          label: 'Similarity threshold'
        max_results:
          type: integer
          label: 'Max results'
        boost_exact_matches:
          type: boolean
          label: 'Boost exact matches'
    
    performance:
      type: mapping
      label: 'Performance configuration'
      mapping:
        azure_optimized:
          type: boolean
          label: 'Azure optimized'
        connection_pool_size:
          type: integer
          label: 'Connection pool size'
        statement_timeout:
          type: integer
          label: 'Statement timeout'
        work_mem:
          type: string
          label: 'Work memory'
        effective_cache_size:
          type: string
          label: 'Effective cache size'
        shared_buffers:
          type: string
          label: 'Shared buffers'
        maintenance_work_mem:
          type: string
          label: 'Maintenance work memory'